name: quay-dockerfiles-check
on:
  push:
    branches:
      - main
  pull_request:
    branches:
    - main
jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Checkout code
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
    - name: Check dockerfiles
      run: |
              make quay-dockerfiles
              test -z "$(git status --porcelain)" || (echo "please run 'make quay-dockerfies', and submit your changes"; exit 1)

